package samplerequest;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainMenu1.java
 *
 * Created on Mar 24, 2010, 7:35:30 PM
 */

/**
 *
 * @author root
 * /*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */



import java.io.*;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
 class Pair {
    private String first;
    private int second;

    public Pair(String first, int second) {
        super();
        this.first = first;
        this.second = second;
    }

    @Override
    public String toString()
    {
           return "(" + first + ", " + second + ")";
    }

    public String getFirst() {
        return first;
    }

    public void setFirst(String first) {
        this.first = first;
    }

    public int getSecond() {
        return second;
    }

    public void setSecond(int second) {
        this.second = second;
    }
 
 }
 
 /**
  *
  * @author sathishac
  */
 public class MainMenu extends javax.swing.JFrame {

int Thprocess=0;
double Thppload=0.0;
 double Thcpuload =0.0;
 double Thtraffic=0.0;
 double time=0.0;
 int accesses = 0;
 String Target ="";
String unit="";
    /** Creates new form MainMenu1 */
    public MainMenu() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();

        jButton6.setText("Set Process Limit");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Find  the target network");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("whether overloaded?");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Current Status");

        jButton3.setText("Set Thresholds");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextField1.setText("0.3");

        jTextField2.setText("1");

        jLabel2.setText("No Of Processes            : ");

        jLabel3.setText("process");

        jLabel4.setText("CPU Load                       :");

        jLabel5.setText("CPUload");

        jLabel6.setText("process");

        jLabel7.setText("CPU  load");

        jLabel8.setText("LIMIT ");

        jLabel9.setText("CURRENT");

        jLabel10.setText("TRAFFIC ( in MB)");

        jLabel11.setText("LOAD  LIMIT :");

        jButton4.setText("migrate");

        jButton5.setText("Exit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("DejaVu LGC Sans", 0, 24));
        jLabel12.setText("    DYNAMIC LOAD DETECTOR AND BALANCER");

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 18));
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));

        jLabel14.setForeground(new java.awt.Color(241, 26, 26));
        jLabel14.setText("NETWORK ADDRESS");

        jLabel15.setText("MAXIMUM REQESTS IS FROM");

        jLabel16.setText("TOTAL ACCESSES");

        jTextField3.setText("4000");

        jLabel17.setText("Sampling Time    :");

        jLabel18.setForeground(new java.awt.Color(17, 207, 7));
        jLabel18.setText("ms");
        jLabel18.setOpaque(true);

        jLabel20.setText("TRAFFIC                        : ");

        jLabel21.setText("0.0");

        jLabel22.setText("0.0");

        jLabel23.setText("REQUESTS / SECOND    :");

        jLabel24.setText("0.0");

        jLabel25.setText("0.0");

        jLabel19.setText("NO OF ACTIVE PROCESS");

        jTextField4.setText("10");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGap(29, 29, 29))
                                        .addComponent(jLabel16))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel19))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(58, 58, 58)
                                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                            .addComponent(jTextField1)
                                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                            .addComponent(jTextField3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel20)
                                                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(28, 28, 28))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                                .addGap(139, 139, 139)
                                                .addComponent(jLabel15)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel8)
                                                    .addComponent(jLabel21)
                                                    .addComponent(jLabel24)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jLabel5)
                                                            .addComponent(jLabel3))))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel25)
                                                    .addComponent(jLabel22)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel9))
                                                .addGap(15, 15, 15))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(53, 53, 53))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(258, 258, 258)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(568, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(450, 450, 450))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel11)
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel22)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel7)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel25)))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jButton3)
                                    .addComponent(jButton1)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16)))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton2)
                                    .addComponent(jButton4))
                                .addGap(18, 18, 18)
                                .addComponent(jButton5))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new viewloader().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        PrintWriter fwrite =null;
        try {
            // TODO add your handling code here:
            
            Thcpuload = Double.parseDouble(jTextField1.getText());
            jLabel3.setText(jTextField2.getText());

            Thtraffic = Double.parseDouble(jTextField2.getText());
            jLabel5.setText(jTextField1.getText());
            
            accesses = Integer.parseInt(jTextField3.getText());

            Thprocess = Integer.parseInt(jTextField4.getText());

            jLabel18.setText(jTextField3.getText() + "ms");
           // accesses = Integer.parseInt(jTextField3.getText());
            
            fwrite = new PrintWriter(new FileWriter("variables.txt"));
            
            System.out.println("Th = "+Thprocess);
            //bfout.flush();
            System.out.println(" i am here" );
            fwrite.println(Thcpuload);
            fwrite.println(Thtraffic);
            fwrite.println(accesses);
            fwrite.print(Thprocess);
               System.out.println( "cpuload = "+Thcpuload + "\ntraffic =  "+Thtraffic +"\nThaccesses = "+accesses+"\nThprocesses = "+Thprocess  );
            //fwrite.println();
            //bfout.write((byte)Thcpuload);
            //bfout.write((byte)Thtraffic);
            //bfout.write((byte)time);

            fwrite.close();

        } catch (Exception ex) {
            System.out.print(ex);
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }  finally {
            
        }
        



    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           FileInputStream fin = null;
          
        try {



            for (int ll=0 ; ll<100;ll++)
            {
                    int n;

                    String str = "";
                    String cmd = "";
                    String ip = "";
                    String filepath = "/var/log/apache2/access.log";
                    String filepath2 = "/root/PROJECT/fileout";
                    fin = new FileInputStream(filepath);
                    FileOutputStream fout = new FileOutputStream(filepath2);
            Pair count;
            Vector<Pair> data = new Vector<Pair>();
            Vector<Pair> request_size = new Vector<Pair>();
            Vector<Pair> reply_size = new Vector<Pair>();


/*	String var[] = str1.split(" ");
	String temp  =	var[7].replace("%"," ");
	temp = temp.trim();
	System.out.println("var 5 = " + var[7]) ;
 double cpu_load = Double.parseDouble(temp);
	System.out.println("var 5 = " + temp);
            while( ( n1 = fin1.read() ) != '\n' )
                                  str1 = str1 + (char)n1 ;
	System.out.println(str1);*/

//String[] cpu = var[5].split(">");
//	System.out.println("cpu =  "+cpu[8]);

//	 while( ( n1 = fin1.read() ) != '\n' )
  //                str1 = str1 + (char)n1 ;
    //        System.out.println(str1+"\n");

//		for(int network = 0 ; network < no_of_network ; network ++ )
//         IP[0]="127.0.0.1";
//for (int i=0;i<Thprocess;i++)

   //         for(;;)

                cmd = "";
                str = "./ip ";
                ip = "";
                String input="";
                try {
                    while ((n = fin.read()) != '\n') {
                        input = input + (char) n;
                    }
                } catch (IOException ex) {
                    Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
                }
                String[] vars = input.split(" ");
                ip =vars[0];
                int ref_size =  Integer.parseInt(vars[10]);
                int rep_size =  Integer.parseInt(vars[11]);
                cmd = "./ip " + ip + " 255.255.15.0";
                String line = "";
                try {
                    System.out.println(cmd);
                    Runtime run = Runtime.getRuntime();
                    Process pr = run.exec(cmd);
                    pr.waitFor();

                    BufferedReader buf = new BufferedReader(new InputStreamReader(pr.getInputStream()));
                    while ((line = buf.readLine()) != null) {
                        fout.write(line.getBytes());
                        fout.write(("\n").getBytes());
                        ip = line.toString();
                    }

                } catch (Exception e) {
                    System.out.println(e);
                }
                System.out.println("ip address " + ip + "input: " + ref_size + " rep_size : " + rep_size + " \n");
                int j;
                Boolean flag = false;
                System.out.println(ip);



//FIND AND SAVE NETWORK ADDRESS , REQUEST SIZE , REPLY SIZE FROM EACH NETWORK


                for (j = 0; j < data.size(); j++)
                            {
                                        Pair temp1 = data.get(j);
                                        Pair temp2 = request_size.get(j);
                                        Pair temp3 = reply_size.get(j);
                                        if (temp1.getFirst().equals(ip))
                                        {
                                                    int c = temp1.getSecond();
                                                    int req = temp2.getSecond();
                                                    int rep = temp3.getSecond();
                                                    temp1.setSecond(c + 1);
                                                    temp2.setSecond(req + ref_size);
                                                    temp3.setSecond(rep + rep_size);
                                                    flag = true;
                                                    break;
                                        }
                            }
                if (flag == false)
                {
                            Pair temp1 = new Pair(ip, 1);
                            data.add(temp1);
                            Pair temp2 = new Pair(ip, ref_size);
                            request_size.add(temp2);
                            Pair temp3 = new Pair(ip, rep_size);
                            reply_size.add(temp3);
                }



    //LOAD CALCULATION


                int process = 0;
                int request = 0;
                int reply = 0;

               Pair maxreq= new Pair("0.0.0.0",0);
               for (int k = 0; k < data.size(); k++)
               {
                                Pair temp1 = data.get(k);
                                process += temp1.getSecond();
                                request += request_size.get(k).getSecond();

                                if(request_size.get(k).getSecond()>maxreq.getSecond())
                                            maxreq=request_size.get(k);

                                reply += reply_size.get(k).getSecond();


                }


               double ppload = (double) (reply) / (process * request);

                jLabel6.setText(Integer.toString(process));
                jLabel7.setText(Double.toString(ppload));

                System.out.println("  ppload = " + (double) (reply) / (process * request) + "Thppload = " + Thppload + "process" + process + "Thprocess = " + Thprocess);

   System.out.println("System currently overloaded due to more requests");
                        jLabel6.setText(Integer.toString(process));
                        jLabel7.setText(Double.toString(ppload));
                        jLabel13.setText("oops !!! I am overloaded !!!");

                if (process > Thprocess && ppload > Thppload) {

                    System.out.println("System currently overloaded due to more requests");
                        jLabel6.setText(Integer.toString(process));
                        jLabel7.setText(Double.toString(ppload));
                        jLabel13.setText("oops !!! I am overloaded !!!");



     //ACTION TO BE PERFORMN

                        jLabel14.setText(maxreq.getFirst());
                        jLabel14.setText("localhost");
                        Target =  maxreq.getFirst();
                        System.out.println(Target);
                    break;
                }
//            }
         //   int process = 0;
            for (int k = 0; k < data.size(); k++) {
                Pair temp1 = data.get(k);
                System.out.println("IP address : " + temp1.getFirst() + "  count = " + temp1.getSecond());
                process += temp1.getSecond();
                temp1 = request_size.get(k);
                System.out.println("IP address : " + temp1.getFirst() + "  request_size = " + temp1.getSecond());
                temp1 = reply_size.get(k);
                System.out.println("IP address : " + temp1.getFirst() + "  reply_size = " + temp1.getSecond());
            }

        }
        }
        catch (Exception ex) {
                Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
            }
            



    }//GEN-LAST:event_jButton1ActionPerformed
        
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
                
            }

        });
    }
    
    @Override
    public void dispose() {
        super.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

}
